2021/01/20 20:48:43 [error] 521#521: *92 FastCGI sent in stderr: "Traceback (most recent call last):
  File "/var/www/html/scripts/dashboard_json.py", line 91, in <module>
    build_data_json(data_array)
  File "/var/www/html/scripts/dashboard_json.py", line 26, in build_data_json
    activ_uid = get_user_id(data_array)
  File "/var/www/html/scripts/files/get_data.py", line 59, in get_user_id
    return result[0][0]
IndexError: list index out of range" while reading response header from upstream, client: 185.162.223.195, server: dhbwdach.ddns.net, request: "POST /scripts/dashboard_json.py HTTP/1.1", upstream: "fastcgi://unix:/var/run/fcgiwrap.socket:", host: "dhbwdach.ddns.net", referrer: "https://dhbwdach.ddns.net/scripts/main.py"
2021/01/20 20:49:43 [error] 521#521: *92 FastCGI sent in stderr: "Traceback (most recent call last):
  File "/var/www/html/scripts/dashboard_json.py", line 91, in <module>
    build_data_json(data_array)
  File "/var/www/html/scripts/dashboard_json.py", line 26, in build_data_json
    activ_uid = get_user_id(data_array)
  File "/var/www/html/scripts/files/get_data.py", line 59, in get_user_id
    return result[0][0]
IndexError: list index out of range" while reading response header from upstream, client: 185.162.223.195, server: dhbwdach.ddns.net, request: "POST /scripts/dashboard_json.py HTTP/1.1", upstream: "fastcgi://unix:/var/run/fcgiwrap.socket:", host: "dhbwdach.ddns.net", referrer: "https://dhbwdach.ddns.net/scripts/main.py"
2021/01/20 20:50:43 [error] 521#521: *92 FastCGI sent in stderr: "Traceback (most recent call last):
  File "/var/www/html/scripts/dashboard_json.py", line 91, in <module>
    build_data_json(data_array)
  File "/var/www/html/scripts/dashboard_json.py", line 26, in build_data_json
    activ_uid = get_user_id(data_array)
  File "/var/www/html/scripts/files/get_data.py", line 59, in get_user_id
    return result[0][0]
IndexError: list index out of range" while reading response header from upstream, client: 185.162.223.195, server: dhbwdach.ddns.net, request: "POST /scripts/dashboard_json.py HTTP/1.1", upstream: "fastcgi://unix:/var/run/fcgiwrap.socket:", host: "dhbwdach.ddns.net", referrer: "https://dhbwdach.ddns.net/scripts/main.py"
2021/01/20 20:51:43 [error] 521#521: *92 FastCGI sent in stderr: "Traceback (most recent call last):
  File "/var/www/html/scripts/dashboard_json.py", line 91, in <module>
    build_data_json(data_array)
  File "/var/www/html/scripts/dashboard_json.py", line 26, in build_data_json
    activ_uid = get_user_id(data_array)
  File "/var/www/html/scripts/files/get_data.py", line 59, in get_user_id
    return result[0][0]
IndexError: list index out of range" while reading response header from upstream, client: 185.162.223.195, server: dhbwdach.ddns.net, request: "POST /scripts/dashboard_json.py HTTP/1.1", upstream: "fastcgi://unix:/var/run/fcgiwrap.socket:", host: "dhbwdach.ddns.net", referrer: "https://dhbwdach.ddns.net/scripts/main.py"
2021/01/20 20:51:58 [error] 521#521: *103 FastCGI sent in stderr: "PHP message: PHP Warning:  "continue" targeting switch is equivalent to "break". Did you mean to use "continue 2"? in /usr/share/phpmyadmin/libraries/config/FormDisplay.php on line 660" while reading response header from upstream, client: 185.162.223.195, server: dhbwdach.ddns.net, request: "GET /phpmyadmin/index.php?token=99470becba84c673c4617bc5d0f5019f HTTP/1.1", upstream: "fastcgi://unix:/var/run/php/php7.3-fpm.sock:", host: "dhbwdach.ddns.net"
2021/01/20 20:52:43 [error] 521#521: *92 FastCGI sent in stderr: "Traceback (most recent call last):
  File "/var/www/html/scripts/dashboard_json.py", line 91, in <module>
    build_data_json(data_array)
  File "/var/www/html/scripts/dashboard_json.py", line 26, in build_data_json
    activ_uid = get_user_id(data_array)
  File "/var/www/html/scripts/files/get_data.py", line 59, in get_user_id
    return result[0][0]
IndexError: list index out of range" while reading response header from upstream, client: 185.162.223.195, server: dhbwdach.ddns.net, request: "POST /scripts/dashboard_json.py HTTP/1.1", upstream: "fastcgi://unix:/var/run/fcgiwrap.socket:", host: "dhbwdach.ddns.net", referrer: "https://dhbwdach.ddns.net/scripts/main.py"
2021/01/20 20:53:43 [error] 521#521: *92 FastCGI sent in stderr: "Traceback (most recent call last):
  File "/var/www/html/scripts/dashboard_json.py", line 91, in <module>
    build_data_json(data_array)
  File "/var/www/html/scripts/dashboard_json.py", line 26, in build_data_json
    activ_uid = get_user_id(data_array)
  File "/var/www/html/scripts/files/get_data.py", line 59, in get_user_id
    return result[0][0]
IndexError: list index out of range" while reading response header from upstream, client: 185.162.223.195, server: dhbwdach.ddns.net, request: "POST /scripts/dashboard_json.py HTTP/1.1", upstream: "fastcgi://unix:/var/run/fcgiwrap.socket:", host: "dhbwdach.ddns.net", referrer: "https://dhbwdach.ddns.net/scripts/main.py"
